### ISSUE TITLE
Incorrect header file name

### ISSUE THREAD

**Issue by kunal-mod** [Solo-FL/SOLO-motor-controllers-CPP-library#1]
In the header files SOLOMotorControllersSerial.h and SOLOMotorControllersUtils.h there is capitalization mistake while including the header file #include "SOLOMotorControllers.h". The correct name for this header file should be #include "SoloMotorControllers.h" or the header file in the src folder can be renamed from SoloMotorControllers.h toSOLOMotorControllers.h

**Comment by Solo-FL** [comment]
file changed to the correct SOLOMotorControllers.h
